version: '3.8'

services:

  dev-db-new:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=mike
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=tstproj
    ports:
        - "8000:5432"
    volumes:
      - pgdata-catalog:/var/lib/postgresql/data
volumes:
  pgdata-catalog:

